# Generated by Django 6.0.1 on 2026-01-23 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_systemsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('total_samples', models.IntegerField(default=0)),
                ('epochs', models.IntegerField(default=0)),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('val_accuracy', models.FloatField(blank=True, null=True)),
                ('model_size_mb', models.FloatField(blank=True, null=True)),
                ('log_output', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
