# Generated by Django 6.0.1 on 2026-01-23 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_dataset_file_types_dataset_processed_files_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='preview_image',
            field=models.ImageField(blank=True, null=True, upload_to='mri_previews/%Y/%m/%d/'),
        ),
    ]
