# Generated by Django 6.0.1 on 2026-01-24 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='patient_age',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='analysis',
            name='patient_gender',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='analysis',
            name='patient_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='analysis',
            name='scan_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
