# Generated by Django 6.0.1 on 2026-01-24 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_analysis_patient_age_analysis_patient_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingsession',
            name='current_epoch',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='current_stage',
            field=models.CharField(default='PENDING', max_length=100),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='progress_percent',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='total_epochs',
            field=models.IntegerField(default=0),
        ),
    ]
